### ISSUE TITLE
Rally Migration 

### ISSUE THREAD

**Issue by jthennings** [stbauer8/DevOps-Tiger-Team#8]
Migrate project level release activities to Rally

**Comment by stbauer8** [comment]
Provider Payments Initial Rally Access List:

Program (Read Access to: CCRS/FBCS/PIT):  Dawn Saddler 
CCRS:  Jennifer Hamm / Seema Chaudhry / Michelle Manogue-Gilbertson / Bobby (Robert) Hidy / Jim (James) Reich 
FBCS:   Jennifer Hamm / Laurie Washburn / Mona Haeri (VA Access and GFE are pending)  / Bob (Robert) Rupe
PIT:   Darnell Clark  / Laurie Washburn / Ted (Theodore) Ritenour
